### ISSUE TITLE
GPIO not working with rPi 2/3

### ISSUE THREAD

**Issue by Saiyato** [Saiyato/volumio-hd44780-plugin#2]
GPIO not working with rPi 2/3

**Comment by Saiyato** [comment]
Recompiled driver, needs testing

**Comment by hassfers** [comment]
i have tried it today an i doesn't work. there are only some cryptical Symbols.

**Comment by Saiyato** [comment]
I'm going to need a little more information than 'it doesn't work' ;)
What is your hardware setup? 
Which software versions are you using?
How is your LCD connectect, I'm assuming over GPIO, but which GPIO's are you using?

Sometimes you need to restart, does this help?

**Comment by hassfers** [comment]
sorry :) it shows stupid chars or groups of it. 
i have got a pi 2 and a HD44780 connected over GPIO pins. and what is the BL pin for?
im using the default GPIO pins shown on the setting page. 

and a restart doesn't help for me.

**Comment by Saiyato** [comment]
Hey, ok, that helps. I'm assuming you're using Volumio as OS (since it's a Volumio plugin, but can be used on any Jessie distro)?

The BL pin is for backlight, you will need this in case of non-oled LCD screens.

Can you post a picture of how you connected your screen and what the screen shows?

**Comment by hassfers** [comment]
after a huge amount of testing i get it back to work. 
No idea what i have done wrong before. Sorry.
now i have a solid "picture" but there is always
"Welcome t 
 VOLUMIO 2" 
on the display. did i miss some settings for printing out song information 
![img_7808](https://user-images.githubusercontent.com/27955167/30162376-d678d264-93d4-11e7-884d-fd7abbb41a3f.jpg)

**Comment by Saiyato** [comment]
Hi,

Is the LCDd process running? And the mpdlcd component?
I must say I haven't touched this code in a very long time... so it takes a little time to read into this

**Comment by hassfers** [comment]
sorry for the late reply i have to start the mpdlcd component manual and after a few tries with different cables i works. thanks 

one thing is it possible to configure what is displayed ?

**Comment by Saiyato** [comment]
Great news! 

I believe mpdlcd should autostart automatically, it's a python script and I don't really know how that works. You can edit what is displayed in the mpdlcd.conf file (found in /etc/).

I don't think I will patch much more in this version, since it requires too much other software. I will release a new plugin for the displays later on.
