### ISSUE TITLE
GPIO not working with rPi Zero W

### ISSUE THREAD

**Issue by antiprism** [Saiyato/volumio-hd44780-plugin#3]
Wiring a 16x2 LCD to a Raspberry PI Zero W using the GPIO connection method produces no output on the LCD. I can see that LCDd is running, but he test command 'lcdproc C' also produces no output.

Following the report here

   https://github.com/lcdproc/lcdproc/issues/86

I built and installed libugpio, then built the lcdproc from the git repository, and using this version of LCDd with ConnectionType=gpio, the plugin will now display track details to the LCD.

**Comment by romeok01** [comment]
On Pi Zero the LCD does not work. Please help

**Comment by antiprism** [comment]
Did you try the steps I posted?

**Comment by romeok01** [comment]
I can't, please write me, what i have to do.

**Comment by antiprism** [comment]
Have you built and installed libugpio?

**Comment by romeok01** [comment]
I cant build and install libugpio, how to install and build libugpio?

**Comment by antiprism** [comment]
As in my original post, you also have to build and install the latest lcdproc from the git repository and use that version of LCDd.
