### ISSUE TITLE
display works but no track titles

### ISSUE THREAD

**Issue by jotka** [Saiyato/volumio-hd44780-plugin#4]
Hi 
Thanks for a great plugin, saved me a lot of time with drivers, config etc.
I have a 40x4 IC2 display. It works, after installing the plugin and configuration, it displays "hello, welcome to Volumio2" etc. Works fine if I play Flac tracks from my NAS. But doesn't work with Spotify plugin. Then, after a while only "--:--  [. --:--" Weird, looks like volumio/mpd do not expose the Spotify track to lcdproc. Can you please help with the debugging?

**Comment by jotka** [comment]
haha, I think I need to fetch the info about a track playing from spopd and throw it at the display :) 
I'll get my hands dirty, expect a PR ;)

**Comment by fritsypeij** [comment]
That would be awesome!
