### ISSUE TITLE
Volumio 2.411 and newer are using a new Node.js version

### ISSUE THREAD

**Issue by JulianBastel** [Saiyato/volumio-hd44780-plugin#5]
The plugin will no work with Volumio 2.411 because i2c-bus complains that

"The module 'data/plugins/miscellanea/HD44780/mode_modules/i2c-bus/build/Release/i2c.mode'  
was compiled agains a diffrent Node.js version using 
....

To solve the problem, a newer version of i2c-bus is required unfortunately the package.json is not complete. 

Add the following dependencies:

"i2c-bus": "^3.2.0",
"onoff": "^3.1.0",
"lcd": "^2.0.3",
"lcdi2c": "^1.0.6",
"q": "^1.5.1",
"sleep": "^5.1.1"

create a new package and install it.

**Comment by Saiyato** [comment]
Nice work, thanks! I will update the package (untested) today and test tonight.
I suppose this will break installation on versions < 2.411?

**Comment by Saiyato** [comment]
Seems to be working with the latest update
