### ISSUE TITLE
Pluging failing to start in Volumio 2.413

### ISSUE THREAD

**Issue by Redfloyd7800** [Saiyato/volumio-hd44780-plugin#6]
Hi, 
on a fresh volumio install, I tried to install the plugin. The installation went ok, but then the plugin won't start when set to ON on the plugin page.
![image](https://user-images.githubusercontent.com/40927178/42416138-b967a55c-8234-11e8-849d-4a0c8dbce20c.png)

**Comment by Saiyato** [comment]
Did you try the myVolumio image or the "normal" 2.413 image?
Also can you post the log lines from the time you tried to start the plugin and provide insight in how you installed it?

Please note that this plugin is discontinued, you'd better use pydPiper.

**Comment by sico33** [comment]
En que version de volumio funciona el plugin ? Saludos y gracias

**Comment by Saiyato** [comment]
Discontinued plugin
