### ISSUE TITLE
Install Question

### ISSUE THREAD

**Issue by rh1017** [Saiyato/volumio-hd44780-plugin#7]
Hi Saiyato,
Thanks for your work with the hd44780 display.
I am having trouble iinstalling on Volumio 520
What files do I need to download from Github?
I have tried just downloading volumio-hd44780-zip and running "volumio plugin install" which fails.
Should I download a zip of the Branch master?
Your help with the ssh commands to download would be much appreciated.

**Comment by rh1017** [comment]
Correction: Meant Volumio 2.502 -2018-10-31

**Comment by Saiyato** [comment]
Try this:

1. download plugin zip
2. unzip
3. remove the zip file you downloaded
4. install build-essential (if not already done, otherwise skip this step)
5. npm i
6. volumio plugin install

**Comment by rh1017** [comment]
Thanks for your reply Saiyato,
I am new to working in Linux/Raspian but learning slowly.
In 1. do you mean just volumio-hd44780-plugin.zip from the master?
After "install build-essential" I received install: missing destination file operand after 'build essential'
(Does this indicate build-essential is already done?}
npm i gave two warnings HD44780@1.0.10 No repository field. and HD44780@1.0.10 No license field.
Further help appreciated then i'll do a fresh install

**Comment by Saiyato** [comment]
1. the zip file as hosted, not the master.

Are you installing build-essential with sudo rights? This is necessary for Volumio installations.
Note: this plugin is not really plug-and-play, you will need to get your hands dirty ;)

**Comment by rh1017** [comment]
Hi Saiyato,

Many thanks for the additional advice. I will follow your notes in a fresh install.

Meantime, I followed the install procedure for your volumio-pydpiper-plugin on github and had success using an HD44780 display panel and pages_lcd_16x2.py

The only problem was documented display corruption after 1min30 due to a second instance of pydPiper starting. Removing and reconnecting  the 5Volts to the display restarts pydPiper and is stable for the rest of the session.

Have you identified what causes this and is there a fix or work around?

Looking forward to your comments.

Regards,
Richard.

**Comment by Saiyato** [comment]
I'm not sure what you are experiencing exactly and how the installation went, but the script should make sure pydPiper is not started automatically. Do you have a log of the installation?

**Comment by rh1017** [comment]
The plug-in is installed without problems and can be configured through the Volumio UI correctly.

The problem is that after boot pydPiper starts normally then after about 1min30secs the display becomes corrupted. I have seen this mentioned in various other posts where users note that a second instance of pydPiper has started.

Removing and reconnecting the 5V to the display restarts pydPiper and the display is stable until the next reboot
